---
- name: Running custom commands
  shell: app/console {{item.command}} --env={{deploy.project.php.symfony2.env}} {{item.args}} {{deploy.project.php.symfony2.console_opts}}
  args:
    chdir: "{{deploy.project.root}}/releases/{{project_deploy_date.stdout}}"
  with_items: deploy.project.php.symfony2.custom_commands