---
- name: Doctrine schema update
  shell: app/console doctrine:schema:update --force --env={{deploy.project.php.symfony2.env}} {{deploy.project.php.symfony2.console_opts}}
  args:
    chdir: "{{deploy.project.root}}/releases/{{project_deploy_date.stdout}}"